### ISSUE TITLE
can't work on latest rust version  1.90.0

### ISSUE THREAD

**Issue by flyingzl** [logankeenan/axum-cloudflare-adapter#101]
## My cargo.toml
```
├── axum v0.8.4
├── axum-cloudflare-adapter v0.14.0
├── axum-extra v0.10.1
├── console_error_panic_hook v0.1.7
├── oneshot v0.1.11
├── serde v1.0.227
├── serde_json v1.0.145
├── serde_urlencoded v0.7.1
├── tower-service v0.3.3
├── url v2.5.7
├── wasm-bindgen-futures v0.4.54
└── worker v0.5.0
```

## Error
```
wrangler dev

[.....]

⎔ Starting local server...
✘ [ERROR] service core:user:health: Uncaught TypeError: (void 0) is not a function

    at null.<anonymous> (index.js:541:11) in q
    at null.<anonymous> (index.js:546:1)
```

## codes
```rust
use worker::*;
use axum::{
    response::{Html},
    routing::get,
    Router as AxumRouter,
    extract::State,
};
use axum_cloudflare_adapter::{to_axum_request, to_worker_response, wasm_compat, EnvWrapper};
use tower_service::Service;
use std::ops::Deref;

#[derive(Clone)]
pub struct AxumState {
    pub env_wrapper: EnvWrapper,
}

#[wasm_compat]
async fn index(State(state): State<AxumState>) -> Html<&'static str> {
    let env: &Env = state.env_wrapper.env.deref();
    let worker_rs_version: Var = env.var("WORKERS_RS_VERSION").unwrap();
    console_log!("WORKERS_RS_VERSION: {}", worker_rs_version.to_string());
    Html("<p>Hello from Axum!</p>")
}

#[event(fetch)]
pub async fn main(req: Request, env: Env, _ctx: worker::Context) -> Result<Response> {
    let mut _router: AxumRouter = AxumRouter::new()
        .route("/", get(index))
        .with_state(AxumState {
            env_wrapper: EnvWrapper::new(env),
        });
    let axum_request = to_axum_request(req).await.unwrap();
    let axum_response = _router.call(axum_request).await.unwrap();
    let response = to_worker_response(axum_response).await.unwrap();
    Ok(response)
}
```

**Comment by flyingzl** [comment]
this crate can be placed by the latest official  `worker-rs` crated,  `axum_cloudflare_adapter` is not needed any more
